// GENERATO — non si scrive a mano.  npm? no: lo rifà lo script in docs/VIDEO.md
//
// Quali esercizi hanno un video locale in clip/. Serve al player per
// sapere se disegnare il riquadro o lasciare spazio alle istruzioni:
// chiedere il file e scoprire dal 404 che non c'è vorrebbe dire un buco
// nero per mezzo secondo a ogni esercizio scoperto.
export const CLIP = new Set([
  "A1",
  "A2",
  "A3",
  "B1",
  "B2",
  "B3",
  "g1-chin-tuck",
  "g1-elevatore",
  "g1-flex-attiva",
  "g1-scaleno",
  "g2-achilleo",
  "g2-calf-att",
  "g2-calf-ecc",
  "g2-calf-roll",
  "g2-calf-wall",
  "g3-ham-att",
  "g3-ham-din",
  "g3-knight-ham",
  "g4-forward-lunge",
  "g4-hip-axle",
  "g4-knight",
  "g4-samson",
  "g5-0-90",
  "g5-9090",
  "g5-hip-rot",
  "g5-piriforme",
  "g5-t-hip",
  "g5-v-sit",
  "g5-v-stretch",
  "g6-glute-att",
  "g6-glute-roll",
  "g8-back-roll-oh",
  "g8-blackburn",
  "g8-cat-cow",
  "g8-lat-att",
  "g8-lat-roll",
  "g8-lower-back-roll",
  "g8-overhead-att",
  "g8-pec",
  "g8-pec-smash",
  "g8-prayer",
  "g8-prayer-lat-att",
  "g8-shoulders-global",
  "l-abduzione-cavo",
  "l-aslr-zav",
  "l-copenhagen",
  "l-cossack",
  "l-goblet",
  "l-jefferson",
  "l-overhead",
]);
